description: >
  DevOps learner
  - Open-source software enthusiast
  - House music
title: Bastiaan's small blog
email: me@bastiaa.nl
description: >- # this means to ignore newlines until "baseurl:"
  DevOps learner
  Open-source software enthusiast
  House music
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://bastiaa.nl" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:categories/:title/
