author: "Bastiaan Mourik"

title: Bastiaan's small blog
email: me@bastiaa.nl
description:
  DevOps learner \n
  Open-source software enthusiast \n
  House music


theme: minima

# Minima social links
twitter_username: jekyllrb
github_username: bchm
linkedin_username: mourik
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%d-%m-%Y"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
